# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Set the OS, Python version, and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the "docs/readthedocs" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# # Optionally, build localization as well
# formats:
#   - pdf
#   - epub

# Python requirements for building docs
python:
  install:
    - requirements: docs/requirements.txt
